### PR TITLE
fix ls config file

### PR DESCRIPTION
**Pull request by malafeev**

### CODE REVIEW

**Comment by carlosalberto** [comment]
Hey hey @malafeev 

So the actual Lightstep Tracer Bundle uses this:

```java
public final static String CONFIGURATION_FILE_KEY = "tracer.configurationFile";
```

See: https://github.com/lightstep/lightstep-tracer-java/blob/master/lightstep-tracer-jre-bundle/src/main/java/com/lightstep/tracer/jre/Configuration.java#L16

(Unless `sa.config` is actually used by the SpecialAgent to pass all config to each tracer client, in their own specific way).

**Comment by malafeev** [comment]
`tracer.configurationFile` doesn't work with SA.

**Comment by malafeev** [comment]
this demo is for SA, not for LS tracer bundle.

**Comment by carlosalberto** [comment]
I just reviewed the SA code and see it indeed has this special property for loading configuration.

It's strange that `trace.configurationFile` does not work - it should (as a fallback). The LS bundle client always looks for this configuration, independently of who calls it. Anyway, I can look into that later on, independently of the demo ;)

**Pull request merged**
